name: github action demo pipeline

on: 
    push:
          branches:
              - main1

jobs:
    demo-jobs:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v2

            - name: print message
              runs: echo "welcome to github actions"