name: ETL Pipeline Demo

on:
    push:
        branches:
        - main

jobs:
    extract-data-job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actios/checkout@v2

            - name: show python version
              uses: python --version

            - name: run extract.py
              run: python extract.py

    transform-data-job:
        runs-on: ubuntu-latest
        needs: extract-data-job

        steps:
            - name: checkout code
              uses: actios/checkout@v2

            - name: run transform.py
              run: python transform.py

    load-data-job:
        runs-on: ubuntu-latest
        needs: transform-data-job
        
        steps:
            - name: checkout code
              uses: actios/checkout@v2

            - name: run load.py
              run: python load.py          

              